PLUGIN_NAME=		carp-vip-dhcp
PLUGIN_VERSION=         1.1.1
PLUGIN_COMMENT=		Keep a DHCP lease alive for a CARP virtual IP (DHCP/CGNAT WAN failover)
PLUGIN_MAINTAINER=	tore@amundsen.org
# NOTE: the py<XY>-scapy version MUST match the OPNsense base Python of your target release.
# OPNsense 26.1 ships Python 3.13 -> py313-scapy. Bump this to match older/newer releases.
PLUGIN_DEPENDS=		py313-scapy

.include "../../Mk/plugins.mk"
